# Generated by Django 2.0.4 on 2018-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('products', '0009_auto_20180612_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tagged', to='tags.Tag'),
        ),
    ]
