# Generated by Django 2.0.4 on 2018-06-18 03:19

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/hmm.png', null=True, upload_to=products.models.product_directory_path),
        ),
    ]
